version: '3.8'
services:
  frontend:
    image: doctorati/glaze:frontend-3.3
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=local
      - NEXTAUTH_URL=${FRONTEND_URL}
    depends_on:
      - backend
  backend:
    image: doctorati/glaze:backend-3.3
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=docker
    depends_on:
      db:
        condition: service_healthy
  pg_db:
    image: doctorati/glaze:pg_database-3.3
    environment:
      POSTGRES_PASSWORD: evolution
      POSTGRES_DB: main
      POSTGRES_USER: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "main"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}
      o: bind