version: '3.8'
services:
  frontend:
    image: doctorati/glaze:frontend-0.7
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=local
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    depends_on:
      - backend
  backend:
    image: doctorati/glaze:backend-0.7
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=docker
      - USER_KEY=${USER_KEY}
    depends_on:
      - db
  
  db:
    image: doctorati/glaze:database-0.7
    environment:
      MYSQL_ROOT_PASSWORD: evolution
      MYSQL_DATABASE: main
    volumes:
      - 'db_data:/var/lib/mysql'
volumes:
  db_data: {}