version: '3.8'
services:
  frontend:
    image: doctorati/glaze:frontend-0.2
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
  backend:
    image: doctorati/glaze:backend-0.2
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env.docker
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  
  db:
    image: doctorati/glaze:database-0.2
    environment:
      MYSQL_ROOT_PASSWORD: evolution
      MYSQL_DATABASE: main
    volumes:
      - 'db_data:/var/lib/mysql'
volumes:
  db_data: {}